TASK: SELECT EMPLOYEES GETTING SALARY GREATER THAN THEIR MANAGER;

select * from employee_manager w,employee_manager m 
where w.manager_id=m.emp_id and w.salary>m.salary;


TASK: SELECT EMPLOYEES GETTING SALARY GREATER THAN 
AVERAGE SALARY OF THE DEPARTMENT THAT ARE WORKING IN.;

--WITH INLINE VIEW
SELECT * FROM EMP A, (SELECT DEPTNO, TRUNC(AVG(SAL)) AV_SAL
                        FROM EMP
                        GROUP BY DEPTNO) B
WHERE A.DEPTNO=B.DEPTNO 
AND A.SAL>B.AV_SAL;                       

--WITH CORRELATED SUBQUERY
SELECT *
FROM EMP A
WHERE A.SAL>(SELECT AVG(B.SAL) FROM EMP B WHERE A.DEPTNO=B.DEPTNO);

--WITH ANALYTIC FUNCTION
SELECT * FROM(
SELECT EMPNO, ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,
AVG(SAL) OVER(PARTITION BY DEPTNO) AVG_SAL
FROM EMP)
WHERE SAL>AVG_SAL;

--WITH WITH+FUNCTION
WITH 
    FUNCTION AVG_SAL(P_DEPTNO NUMBER) RETURN NUMBER AS
        V_AVG_SAL NUMBER;
    BEGIN
        SELECT AVG(SAL)
        INTO V_AVG_SAL
        FROM EMP
        WHERE DEPTNO=P_DEPTNO;
        
        RETURN V_AVG_SAL;
    END AVG_SAL;
SELECT EMPNO,ENAME,JOB,MGR,SAL,DEPTNO
FROM EMP
WHERE SAL>AVG_SAL(DEPTNO);
/